name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_the_book:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cd the-book && cargo build --verbose
    - name: Run tests
      run: cd the-book && cargo test --verbose

  build_minigrep:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cd minigrep && cargo build --verbose
    - name: Run tests
      run: cd minigrep && cargo test --verbose
